- name: Create default config
  copy:
    src: opt/vpnserver/vpn_server.config
    dest: /opt/vpnserver/vpn_server.config

- name: Run server
  service: name=vpnserver state=started

- name: Configure server
  command: "{{ vpn_vpncmd }} {{ item }}"
  with_items:
    # enable L2TP over IPSec
    - "/cmd IPSecEnable /L2TP:yes /L2TPRaw:no /EtherIP:no /PSK:{{ vpn_ipsec_preshared_key }} /DefaultHub:{{ vpn_hub.name }}"
    # disable OpenVPN
    - "/cmd OpenVpnEnable no /ports:1194"
    # disable Keep Alive feature
    - "/cmd KeepDisable"
    # use safe cipher for encryption
    - "/cmd ServerCipherSet ECDHE-RSA-AES128-GCM-SHA256"
    # enable SecureNat mode
    - "/hub:{{ vpn_hub.name }} /cmd SecureNatEnable"
    # configure NAT
    - "/hub:{{ vpn_hub.name }} /cmd SecureNatHostSet /mac:none /ip:{{ vpn_hub.ip }} /mask:{{ vpn_hub.mask }}"
    # configure DHCP
    - >
      /hub:{{ vpn_hub.name }} /cmd DhcpSet
      /start:{{ vpn_hub.dhcp.start }} /end:{{ vpn_hub.dhcp.end }} /mask:{{ vpn_hub.dhcp.mask }}
      /expire:{{ vpn_hub.dhcp.expire }} /gw:{{ vpn_hub.dhcp.gateway }} /dns:{{ vpn_hub.dhcp.dns }}
      /dns2:{{ vpn_hub.dhcp.dns2 }} /domain:none /log:yes /PushRoute:none

- name: Create groups
  command: "{{ vpn_vpncmd }} /hub:{{ vpn_hub.name }} /cmd GroupCreate {{ item }} /RealName:none /Note:none"
  with_items: "{{ vpn_groups }}"

- name: Create users
  command: "{{ vpn_vpncmd }} /hub:{{ vpn_hub.name }} /cmd UserCreate {{ item.name }} /group:{{ item.groups | first }} /RealName:none /Note:none"
  with_items: "{{ vpn_users }}"

- name: Set user passwords
  command: "{{ vpn_vpncmd }} /hub:{{ vpn_hub.name }} /cmd UserPasswordSet {{ item.name }} /password:{{ item.password }}"
  with_items: "{{ vpn_users }}"

