- name: Install required packages
  yum:
    name:
      - openssl-devel
      - readline-devel
      - ncurses-devel
      - gcc
      - "@Development Tools"
      - unzip

- name: Create sources root directory
  file:
    path: "{{ vpn_src_root_path }}"
    state: directory

- name: Download and unpack source archive
  unarchive:
    src: "https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/archive/v{{ vpn_version }}.zip"
    dest: "{{ vpn_src_root_path }}"
    remote_src: true
    creates: "{{ vpn_src_path }}/configure"

- name: Configure, make and install binaries
  shell: ./configure && make install
  args:
    chdir: "{{ vpn_src_path }}"
    creates: "{{ vpn_root }}/vpnserver"

- name: Check vpnserver configured
  stat:
    path: "{{ vpn_root }}/vpn_server.config"
  register: vpn_config

- name: Install SystemD service for server
  copy:
    src: "{{ vpn_src_path }}/systemd/softether-vpnserver.service"
    dest: "/etc/systemd/system/vpnserver.service"
    remote_src: true

- name: Set correct binaries path in VpnServer service
  replace:
    path: "/etc/systemd/system/vpnserver.service"
    regexp: "/opt/"
    replace: "{{ vpn_root }}"
  notify:
    - reload systemd

- name: Configure vpnserver
  include: configure.yml
  when: not vpn_config.stat.exists

- name: Enable SystemD service on boot
  service: name=vpnserver state=started enabled=yes

