- name: Install required packages
  apt:
    name:
      - build-essential
      - gnupg2
      - gcc
    update_cache: yes
    state: present

- name: Download SoftEther VPN Server package
  get_url:
    url: "https://www.softether-download.com/files/softether/v4.42-9798-rtm-2023.06.30-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.42-9798-rtm-2023.06.30-linux-x64-64bit.tar.gz"
    dest: /tmp/softether-vpnserver.tar.gz

- name: Extract SoftEther VPN Server package
  unarchive:
    src: /tmp/softether-vpnserver.tar.gz
    dest: /opt
    remote_src: yes

- name: Run make command to build SoftEther VPN Server
  command: make
  args:
    chdir: /opt/vpnserver

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /opt/vpnserver
    recurse: true
    mode: "0600"
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /opt/vpnserver/vpnserver
    mode: "0700"
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /opt/vpnserver/vpncmd
    mode: "0700"

- name: Copy vpn_server.sh script to /etc/init.d/vpnserver
  copy:
    src: files/vpn_server.sh
    dest: /etc/init.d/vpnserver
    mode: "0755"

- name: Make sure vpnserver is started on boot
  sysvinit:
    name: vpnserver
    state: started
    enabled: yes

- name: Enable IP Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: Configure IP Forwarding Persistently
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"
    create: yes # Add the line if not present

- name: Configure vpnserver
  include_tasks:
    file: configure.yml
